filesets:
  default:
    include:
      - "airmail/*.py"
      - "airmail/commands/*.py"
      - "airmail/services/*.py"
      - "airmail/utils/*.py"
      - "airmail/bash/*.sh"
      - "*.yaml"
    exclude:
    exclude_gitignore: true
    match_mode: "gitlike"

tasks:
  default:
    fileset: default
    clear_screen: true
    queue_events: false
    commands:
      - "pip3 install -e ."

default_task: default
